spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimeZone=UTC
spring.datasource.username=root
spring.datasource.password=154213115Allen
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect



app.jwt.header=Authorization
app.jwt.header.prefix=Bearer
app.jwt.secret=mySecret
app.jwt.expiration=900000

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.time-zone=UTC

app.token.email.verification.duration=360000
app.token.password.reset.duration=360000
app.token.refresh.duration=2592000000
app.velocity.templates.location=/templates/

app.cache.logoutToken.maxSize=1000