server.tomcat.accesslog.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://ujebrnomiyg9cnmz:5w1HRSLn4khK1jMnw1gW@bcwtrcef9ltink9zpkzy-mysql.services.clever-cloud.com:3306/bcwtrcef9ltink9zpkzy
spring.datasource.username=ujebrnomiyg9cnmz
spring.datasource.password=5w1HRSLn4khK1jMnw1gW
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

 spring.datasource.hikari.maximumPoolSize=5
#spring.datasource.hikari.maxLifetime=600000

jwt.secret=secret
jwt.expiration=3600 